### ISSUE TITLE
STS Legacy deprecated with Ehealth Minor release 2020.1.1

### ISSUE THREAD

**Issue by bigjimlefou** [e-Contract/mycarenet#1]
eHealth Minor release 2020.1.1 state STS Legacy as deprecated.

https://status.ehealth.fgov.be/fr/intervention/AXLhFRzPn88tgJqbOGDP
https://status.ehealth.fgov.be/nl/intervention/AXLhFRzPn88tgJqbOGDP

"Deprecated" means they have disabled the old end point.

**Comment by fcorneli** [comment]
The upcoming 2.0.0 release has eHealth WS-Trust STS support.
